// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/marketplace": {
    params: {};
  };
  "/marketplace/:agentId": {
    params: {
      "agentId": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/agents": {
    params: {};
  };
  "/dashboard/transactions": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/deploy": {
    params: {};
  };
  "/network": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/marketplace" | "/marketplace/:agentId" | "/dashboard" | "/dashboard/agents" | "/dashboard/transactions" | "/dashboard/settings" | "/deploy" | "/network" | "/about";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/marketplace.tsx": {
    id: "routes/marketplace";
    page: "/marketplace";
  };
  "routes/marketplace.$agentId.tsx": {
    id: "routes/marketplace.$agentId";
    page: "/marketplace/:agentId";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/agents" | "/dashboard/transactions" | "/dashboard/settings";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.agents.tsx": {
    id: "routes/dashboard.agents";
    page: "/dashboard/agents";
  };
  "routes/dashboard.transactions.tsx": {
    id: "routes/dashboard.transactions";
    page: "/dashboard/transactions";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
  "routes/deploy.tsx": {
    id: "routes/deploy";
    page: "/deploy";
  };
  "routes/network.tsx": {
    id: "routes/network";
    page: "/network";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/marketplace": typeof import("./app/routes/marketplace.tsx");
  "routes/marketplace.$agentId": typeof import("./app/routes/marketplace.$agentId.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.agents": typeof import("./app/routes/dashboard.agents.tsx");
  "routes/dashboard.transactions": typeof import("./app/routes/dashboard.transactions.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/deploy": typeof import("./app/routes/deploy.tsx");
  "routes/network": typeof import("./app/routes/network.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};